### ISSUE TITLE
Copy Fail

### ISSUE THREAD

**Issue by lucaslink** [fortrabbit/craft-copy#1]
Thanks for putting effort into writing this plugin! It's great to see a hosting company put this kind of effort into easing the deployment process.

After having successfully installed the plugin, I encountered this error after running ./craft copy/setup

```
fortrabbit\Copy\exceptions\RemoteException in /site/craft/vendor/fortrabbit/craft-copy/src/services/Ssh.php: 61                

Stack trace:                                                                                      
#0 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(160): fortrabbit\Copy\services\Ssh->exec('php          
vendor/bin/...')                                                                                                     
#1 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(80):                                                   
fortrabbit\Copy\commands\SetupAction->setupRemote()                                                                  
#2 [internal function]: fortrabbit\Copy\commands\SetupAction->run()                                                  
#3 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)                                      
#4 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)                              
#5 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('setup', Array)                  
#6 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('setup', Array)                      
#7 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/setup', Array)                
#8 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('copy/setup', Array)        
#9 /vendor/yiisoft/yii2/base/Application.php(386):                                                                   
yii\console\Application->handleRequest(Object(craft\console\Request))                                                
#10 /craft(22): yii\base\Application->run()                                                                          
#11 {main}
```

Having never run this before I'm not sure which order the plugin runs the various dependencies. It appears all my files are on the server (minus the above exceptions), but the mysqldump hasn't occurred. Not sure where to go from here to get the site up other than scrapping the app and restarting. Suggestions?

**Comment by ostark** [comment]
Hi Lucas,

Thanks for your report!
I'd love to debug this with you. Please ping us in the fortrabbit support chat (I'm available in ~1 hour till 2PM).

Oli

**Comment by ostark** [comment]
Fixed in https://github.com/fortrabbit/craft-copy/commit/b9d28e8ac311d703fb24d3170788a588ff191722

Update (force beta2)
```
composer remove fortrabbit/craft-copy
composer require fortrabbit/craft-copy:^1.0.0-beta
```

Update the package on remote by pushing the composer.json
```
php craft copy/code/up
```

Run db/up  manually
```
php craft copy/db/up
```

**Comment by lucaslink** [comment]
Thanks for the quick reply! This got me a lot closer. I now get the following error when running
`php craft copy/db/up`

`[ERROR] Plugin is not installed on remote.` 
This occurs at the 50% marker during the db upload.

Attempting to check craft copy/info on remote running
`php craft copy/info` 
returns
`Unknown command: copy`

Attempting to run remove on remote I get 
`/usr/local/bin/composer: line 14:  2676 Killed                  php $_SHELL_TOOLS/$name "$@"`

Attempting to run require on remote I get
`/usr/local/bin/composer: line 14:  2701 Killed                  php $_SHELL_TOOLS/$name "$@"`

**Comment by ostark** [comment]
did you run 
```
php craft copy/code/up
```
?

**Comment by lucaslink** [comment]
Yes. Followed your instructions exactly. 
I imported the database manually using another method (sequel pro import) and the site is now working as it is locally, but I'd prefer to make use of this workflow.

**Comment by lucaslink** [comment]
`php craft copy/db/up `

is working flawlessly after manually importing the db on the remote. 

Here is the full code from the Plugin is not installed on remote error:

fortrabbit\Copy\exceptions\PluginNotInstalledException in sites/craft/vendor/fortrabbit/craft-copy/src/services/Ssh.php: 58 

```
Stack trace:                                                                                                         
                                                                                                                     
#0 /vendor/fortrabbit/craft-copy/src/commands/DbUpAction.php(66): fortrabbit\Copy\services\Ssh->exec('php craft      
copy/...')                                                                                                           
#1 [internal function]: fortrabbit\Copy\commands\DbUpAction->run()                                                   
#2 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)                                      
#3 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)                              
#4 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('db/up', Array)                  
#5 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('db/up', Array)                      
#6 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/db/up', Array)                
#7 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('copy/db/up', Array)        
#8 /vendor/yiisoft/yii2/base/Application.php(386):                                                                   
yii\console\Application->handleRequest(Object(craft\console\Request))                                                
#9 /craft(22): yii\base\Application->run()                                                                           
#10 {main}   
```
Maybe this can help debug the error. Thanks again.

**Comment by nickisnoble** [comment]
Also having this issue

**Comment by ostark** [comment]
@lucaslink 
You can try to enable the plugin manually, in the Craft CP or via ssh
````
ssh {your-app}@deploy.us1.frbit.com "php craft plugin/install copy"
```
