### ISSUE TITLE
Setup script generates incorrect ssh_url (Undefined index error)

### ISSUE THREAD

**Issue by KarlBishop** [fortrabbit/craft-copy#100]
When running the setup script `php craft copy/setup` I got an error:

```
 [ERROR] Undefined index: eu-west-1

         yii\base\ErrorException

         in /app/craft/vendor/fortrabbit/craft-copy/src/Actions/SetupAction.php: 68


▓
▓  Stack trace:
▓
▓  #0 /vendor/fortrabbit/craft-copy/src/Actions/SetupAction.php(68):
▓  ostark\Yii2ArtisanBridge\ErrorHandler->handleError()
▓  #1 /vendor/yiisoft/yii2/base/Action.php(94): fortrabbit\Copy\Actions\SetupAction->run()
▓  #2 /vendor/yiisoft/yii2/base/Action.php(94): ::call_user_func_array:{/vendor/yiisoft/yii2/base/Action.php:94}()
▓  #3 /vendor/yiisoft/yii2/base/Controller.php(180): fortrabbit\Copy\Actions\SetupAction->runWithParams()
▓  #4 /vendor/yiisoft/yii2/console/Controller.php(179): ostark\Yii2ArtisanBridge\base\Commands->runAction()
▓  #5 /vendor/yiisoft/yii2/base/Module.php(528): ostark\Yii2ArtisanBridge\base\Commands->runAction()
▓  #6 /vendor/yiisoft/yii2/console/Application.php(180): craft\console\Application->runAction()
▓  #7 /vendor/craftcms/cms/src/console/Application.php(88): craft\console\Application->runAction()
▓  #8 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
▓  #9 /vendor/yiisoft/yii2/base/Application.php(386): craft\console\Application->handleRequest()
▓  #10 /craft(23): craft\console\Application->run()
▓  #11 {main}
▓
```

I eventually realised this is because the script generated an incorrect ssh_url in `/config/craft-copy/fortrabbit.production.yaml`.

It had inserted:

`ssh_url: myappname@deploy.eu-west-1.frbit.com`

But the correct URL for my app is:

`ssh_url: myappname@deploy.eu2.frbit.com`

**Comment by ostark** [comment]
This is strange. Which App name did you enter?

**Comment by KarlBishop** [comment]
I can't post the app name here (because it would identify a client) - I'll email it to you in a sec.

But since you asked - I just tried running the script using my other app names and it works fine for all others.

I think the main differences between the one that doesn't work and the others are:

```
             │ Stack  │ Plan
─────────────┼────────┼──────────
doesn't work │ Pro    │ Trial
works        │ Uni    │ Standard
```

**Comment by ostark** [comment]
Thanks for your report. Please let us continue privately.
