### ISSUE TITLE
Cannot upload database - GLOBAL.GTID_PURGED can only be set when GLOBAL.GTID_MODE = ON

### ISSUE THREAD

**Issue by KarlBishop** [fortrabbit/craft-copy#102]
When I try to run `php craft copy/db/up` I get an error:

```
 [ERROR] The shell command "mysql --defaults-extra-file="/tmp/my.cnf" local <
         "storage/craft-copy-transfer.sql"" failed with exit code 1: ERROR 1839 (HY000) at line 24: @@GLOBAL.GTID_PURGED
         can only be set when @@GLOBAL.GTID_MODE = ON.

         craft\errors\ShellCommandException

         in /app/craft/vendor/craftcms/cms/src/db/Connection.php: 597


▓
▓  Stack trace:
▓
▓  #0 /vendor/craftcms/cms/src/db/Connection.php(343):
▓  craft\db\Connection->_executeDatabaseShellCommand(Object(mikehaertl\shellcommand\Command))
▓  #1 /vendor/fortrabbit/craft-copy/src/Services/Database.php(47): craft\db\Connection->restore('storage/craft-c...')
▓  #2 /vendor/fortrabbit/craft-copy/src/Actions/DbDownAction.php(78):
▓  fortrabbit\Copy\Services\Database->import('storage/craft-c...')
▓  #3 [internal function]: fortrabbit\Copy\Actions\DbDownAction->run('production')
▓  #4 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
▓  #5 /vendor/yiisoft/yii2/base/Controller.php(180): yii\base\Action->runWithParams(Array)
▓  #6 /vendor/yiisoft/yii2/console/Controller.php(179): yii\base\Controller->runAction('db/down', Array)
▓  #7 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('db/down', Array)
▓  #8 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/db/down', Array)
▓  #9 /vendor/craftcms/cms/src/console/Application.php(88): yii\console\Application->runAction('copy/db/down', Array)
▓  #10 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('copy/db/down', Array)
▓  #11 /vendor/yiisoft/yii2/base/Application.php(386):
▓  yii\console\Application->handleRequest(Object(craft\console\Request))
▓  #12 /craft(23): yii\base\Application->run()
▓  #13 {main}
▓
```

**Comment by ostark** [comment]
Which version? Craft, Copy, mysql

**Comment by KarlBishop** [comment]
Craft is latest (now 3.5.18)
Copy 1.0.3

I've just realised there are quite different versions of MySQL in the local and remote environments:
```
Local = PHP 7.3.2, MySQL 5.6.34 (mysqldump  Ver 10.13 Distrib 5.5.62, for debian-linux-gnu (x86_64))
Remote = PHP 7.4.4, MySQL 8.0.20 (mysqldump  Ver 10.13 Distrib 5.7.30, for Linux (x86_64))
```
So maybe that is the issue?
