### ISSUE TITLE
Project configuration causing internal server errors

### ISSUE THREAD

**Issue by rossnorthrup** [fortrabbit/craft-copy#144]
So, the past few times that I have made yaml file changes, I have pushed to production and have received internal server errors on the pages that are due for an update from those files.

My craft logs tell me - Column not found: 1054 Unknown column 'content.field_advisor_advisorName' in 'field list
However, I did not make changes to this field. I made changes to a field that is a 'sibling' of this field. They live side by side in the same structure. I changed 'content.field_advisor_advisorTitle' from a text field to a redactor field.

I don't understand why changes are being applied to different fields or not at all. Everything works fine locally.

Any and all help is appreciated. TY.

My terminal and craft logs are below- 

Terminal - 
`$ git push project master
Enumerating objects: 110, done.
Counting objects: 100% (110/110), done.
Delta compression using up to 12 threads
Compressing objects: 100% (54/54), done.
Writing objects: 100% (56/56), 404.26 KiB | 3.55 MiB/s, done.
Total 56 (delta 46), reused 0 (delta 0), pack-reused 0

Commit received, starting build of branch master

–––––––––––––––––––––––  ∙ƒ  –––––––––––––––––––––––

B U I L D

Checksum:
  25adfb255c088d2d31da98de7e0d26d799886a73

Deployment file:
  not found

Pre-script:
  not found
  0ms

Composer:
  - - -
  Installing dependencies from lock file (including require-dev)
  Verifying lock file contents can be installed on current platform.
  Nothing to install, update or remove
  Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
  Generating optimized autoload files
  
  Carbon 1 is deprecated, see how to migrate to Carbon 2.
  https://carbon.nesbot.com/docs/#api-carbon-2
      You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
  
  3 packages you are using are looking for funding.
  Use the `composer fund` command to find out more!
  
  ▶ Craft auto migrate [START]
  
  ▶ Craft auto migrate [migrate/all]
  
  Checking for pending migrations ...
  No new migrations found. Your system is up to date.
  
  ▶ Craft auto migrate [project-config/apply]
  
  Applying changes from your project config files ...
  - updating matrixBlockTypes.4b0c011c-9733-4b09-8cac-84423d1c9788.fields.8888faa7-a73c-456c-89c0-7cb57543ac78.settings ... 
    - updating matrixBlockTypes.4b0c011c-9733-4b09-8cac-84423d1c9788 ... done
    done
  - updating matrixBlockTypes.5c45505a-7265-4bea-9e8e-fa54084a40c8.fields.b2e44474-7f29-43f0-b435-abdaba13ddb9.settings ... 
    - updating matrixBlockTypes.5c45505a-7265-4bea-9e8e-fa54084a40c8 ... done
    done
  - updating matrixBlockTypes.c913af07-1852-4363-9861-98a489a87a26.fields.9d368b5b-e6e7-40df-8e24-61f32d619c93.settings ... 
    - updating matrixBlockTypes.c913af07-1852-4363-9861-98a489a87a26 ... done
    done
  - updating superTableBlockTypes.34de3b37-4cb8-49da-b565-7812f6b911a1.fields.d26f8df3-7f57-4146-9767-a86bfd1f10b1.settings ... 
    - updating superTableBlockTypes.34de3b37-4cb8-49da-b565-7812f6b911a1 ... done
    done
  - updating superTableBlockTypes.588b9425-c6bd-4337-8a9f-68a87ab153b9.fields.b1a10579-647e-485c-b6d1-695a1e3b62fc.settings ... 
    - updating superTableBlockTypes.588b9425-c6bd-4337-8a9f-68a87ab153b9 ... done
    done
  - updating superTableBlockTypes.90e13a3c-fb96-422c-90a7-69bad5160ad9.fields.9c92fe1d-b143-42a8-a3a9-b4afad0c5dbc.settings ... 
    - updating superTableBlockTypes.90e13a3c-fb96-422c-90a7-69bad5160ad9 ... done
    done
  - updating superTableBlockTypes.d16237a1-7402-4cbd-9dcf-92ec601dd309.fields.6b01cd9c-a877-4106-a6ce-cb8c837d2049.settings ... 
    - updating superTableBlockTypes.d16237a1-7402-4cbd-9dcf-92ec601dd309 ... done
    done
  - updating matrixBlockTypes.5c45505a-7265-4bea-9e8e-fa54084a40c8.fields.b2e44474-7f29-43f0-b435-abdaba13ddb9 ... done
  - updating matrixBlockTypes.4b0c011c-9733-4b09-8cac-84423d1c9788.fields.8888faa7-a73c-456c-89c0-7cb57543ac78 ... done
  - updating dateModified ... done
  Finished applying changes
  
  ▶ Craft auto migrate [END]
  
  - - -
  13s 261ms

Post-script:
  not found
  0ms

R E L E A S E

Packaging:
  9s 54ms

Revision:
  1657744654649240255.25adfb255c088d2d31da98de7e0d26d799886a73

Size:
  64 MB

Uploading:
  996ms

Build & release done in 23s 324ms, now queued for final distribution.
`

Craft Logs - 
`2022-07-13 16:38:11 [-][1][22be38554c1a9d359defe18e469e504b][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: **Column not found: 1054 Unknown column 'content.field_advisor_advisorName' in 'field list'** in /srv/app/project/htdocs/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /srv/app/project/htdocs/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /srv/app/project/htdocs/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT `element...')
#2 /srv/app/project/htdocs/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /srv/app/project/htdocs/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /srv/app/project/htdocs/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all(NULL)
#5 /srv/app/project/htdocs/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1648): craft\db\Query->all(NULL)
#6 /srv/app/project/htdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1566): craft\elements\db\ElementQuery->all()
#7 /srv/app/project/htdocs/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\MatrixBlockQuery), 'all', Array, 'method', false, false)
#8 /srv/app/project/htdocs/storage/runtime/compiled_templates/a8/a81b67d2b75740a49968df299a24be0d0432e73a03fe09226b6a4418897c3b33.php(96): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\MatrixBlockQuery), 'all', Array, 'method')
#9 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2f373b8742fd57bb38138f66e1894b8a679d2454a7b5eea12d749bc16190a095->doDisplay(Array, Array)
#10 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /srv/app/project/htdocs/storage/runtime/compiled_templates/03/03e9f35a26159b09584aab7d2b7ff205a0970725cd6abdb00d5685b1e0d238db.php(97): Twig\Template->display(Array)
#12 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(182): __TwigTemplate_3c501519c043c2c9e6a432f1a862094f60ce762b0c8e0f9a34cc5838ea996376->block_content(Array, Array)
#13 /srv/app/project/htdocs/storage/runtime/compiled_templates/8b/8b2871af2478d9f09c556e007a14f012e95c0e3e0805c4dffcb8b1d83ebe27ae.php(101): Twig\Template->displayBlock('content', Array, Array)
#14 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_34969681dc047765b2a18df011e61a3c6b624d85734345421a03beeee5901372->doDisplay(Array, Array)
#15 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /srv/app/project/htdocs/storage/runtime/compiled_templates/03/03e9f35a26159b09584aab7d2b7ff205a0970725cd6abdb00d5685b1e0d238db.php(43): Twig\Template->display(Array, Array)
#17 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3c501519c043c2c9e6a432f1a862094f60ce762b0c8e0f9a34cc5838ea996376->doDisplay(Array, Array)
#18 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /srv/app/project/htdocs/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#20 /srv/app/project/htdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#21 /srv/app/project/htdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#22 /srv/app/project/htdocs/vendor/craftcms/cms/src/web/View.php(408): Twig\Environment->render('_about/_index', Array)
#23 /srv/app/project/htdocs/vendor/craftcms/cms/src/web/View.php(461): craft\web\View->renderTemplate('_about/_index', Array)
#24 /srv/app/project/htdocs/vendor/craftcms/cms/src/web/Controller.php(201): craft\web\View->renderPageTemplate('_about/_index', Array, 'site')
#25 /srv/app/project/htdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(102): craft\web\Controller->renderTemplate('_about/_index', Array)
#26 [internal function]: craft\controllers\TemplatesController->actionRender('_about/_index', Array)
#27 /srv/app/project/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /srv/app/project/htdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#29 /srv/app/project/htdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#30 /srv/app/project/htdocs/vendor/craftcms/cms/src/web/Application.php(293): yii\base\Module->runAction('templates/rende...', Array)
#31 /srv/app/project/htdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#32 /srv/app/project/htdocs/vendor/craftcms/cms/src/web/Application.php(278): yii\web\Application->handleRequest(Object(craft\web\Request))
#33 /srv/app/project/htdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#34 /srv/app/project/htdocs/web/index.php(22): yii\base\Application->run()
#35 {main}
`

**Comment by rossnorthrup** [comment]
So, my process for fixing this was:

1. Retrieve the production database
2. Importing locally and rebuilding the project config
3. Modifying the db as needed, 
4. FTP'ing in and deleting the project config files, 
5. Importing my local project config files, 
6. Reimporting the db from local to production
7.  Push committed updates.

Hopefully this doesn't keep happening and it was something I overlooked that day.
