### ISSUE TITLE
SSH Remote error: 255 on DDEV when I pull db

### ISSUE THREAD

**Issue by JayBox325** [fortrabbit/craft-copy#184]
I have installed craft-copy and pushed up all code and the db, then to perform my first pull test to make sure everything is running I got the following error when I tried to pull the db. I have seen multiple other `SSH Remote error: 255` issues raised, but none with an unresolved hostname error (`Could not resolve hostname deploy.eu2.frbit.com: Temporary failure in name resolution`).

```
App: app-name-here.frb.io (production)
▏
▏Export DB from fortrabbit, download and import locally.

 Are you sure? (yes/no) [yes]:
 > yes

 [ERROR] SSH Remote error: 255
         Command: ssh app-name-here@deploy.eu2.frbit.com  "php craft copy/db/to-file ./storage/craft-copy-transfer.sql
         --interactive=0"
         Output:
         ssh: Could not resolve hostname deploy.eu2.frbit.com: Temporary failure in name resolution

         fortrabbit\Copy\Exceptions\RemoteException

         in /var/www/html/vendor/fortrabbit/craft-copy/src/Services/Ssh.php: 140

▓
▓  Stack trace:
▓
▓  #0 /vendor/fortrabbit/craft-copy/src/Actions/DbDownAction.php(56): fortrabbit\Copy\Services\Ssh->exec('ssh
▓  app-name-here@...')
▓  #1 [internal function]: fortrabbit\Copy\Actions\DbDownAction->run(NULL)
▓  #2 /vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array(Array, Array)
▓  #3 /vendor/yiisoft/yii2/base/Controller.php(178): yii\base\Action->runWithParams(Array)
▓  #4 /vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('db/down', Array)
▓  #5 /vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('db/down', Array)
▓  #6 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/db/down', Array)
▓  #7 /vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('copy/db/down', Array)
▓  #8 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('copy/db/down', Array)
▓  #9 /vendor/craftcms/cms/src/console/Application.php(122):
▓  yii\console\Application->handleRequest(Object(craft\console\Request))
▓  #10 /vendor/yiisoft/yii2/base/Application.php(384):
▓  craft\console\Application->handleRequest(Object(craft\console\Request))
▓  #11 /craft(13): yii\base\Application->run()
▓  #12 {main}
▓
```

**Comment by frank-laemmer** [comment]
Sorry for the late reply here. One possible solution is that you have upgraded Craft CMS some time ago and the config needs to be manually patched:
https://craftcms.stackexchange.com/a/41423/4504

Another lead might be that this is related to your local setup, specifically are you using DDEV and if so how is that configured?

**Comment by erinbit** [comment]
Temporary DNS issues are common on the internet and depends on a lot of things, local setup, network connection, etc. I'm closing this for now. Feel free to come back with more information if this issue still exists.
