### ISSUE TITLE
Setup for Pro stack app fails: Undefined index: us-east-1

### ISSUE THREAD

**Issue by jasonschock** [fortrabbit/craft-copy#19]
Ubuntu 18.04; PHP 7.2 
`PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug 19 2018 07:16:54) ( NTS )`

App is located at `deploy.us1.frbit.com`.

```
./craft copy/setup

 What's the name of your App? []:
 > <my-app>



 [ERROR] Undefined index: us-east-1

         yii\base\ErrorException

         in /home/vagrant/sites/craft/vendor/fortrabbit/craft-copy/src/commands/SetupAction.php: 54


▓
▓  Stack trace:
▓
▓  #0 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(54): yii\base\ErrorHandler->handleError(8, 'Undefined
▓  index...', '/home/vagrant/s...', 54, Array)
▓  #1 [internal function]: fortrabbit\Copy\commands\SetupAction->run()
▓  #2 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
▓  #3 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
▓  #4 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('setup', Array)
▓  #5 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('setup', Array)
▓  #6 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/setup', Array)
▓  #7 /vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('copy/setup', Array)
▓  #8 /vendor/yiisoft/yii2/base/Application.php(386):
▓  yii\console\Application->handleRequest(Object(craft\console\Request))
▓  #9 /craft(22): yii\base\Application->run()
▓  #10 {main}
```

**Comment by ostark** [comment]
Hi @jasonschock 
thanks for your report and sorry for the late reply. 
Can you tell me which App name you used?

Oli
