### ISSUE TITLE
Setup error SSH issue?

### ISSUE THREAD

**Issue by bryanjhickey** [fortrabbit/craft-copy#34]
Getting this error when running `php craft copy/setup`

The config file exist at [project]/config/fortrabbit.production.yaml so not sure why the error is being thrown?

``` 
What's the name of your fortrabbit App?:
 > intrpk

 What's a good name for the environment of the fortrabbit App? (use arrow keys or type) [production]:
 > stage


Testing DNS - US (AWS US-EAST-1 / Virginia) OK
Testing rsync OK
Testing mysqldump OK
Testing SSH access OK

 [ERROR]

         fortrabbit\Copy\exceptions\DeployConfigNotFoundException

         in /Users/bjh/Code/interpack/api/vendor/fortrabbit/craft-copy/src/services/DeployConfig.php: 128


▓
▓  Stack trace:
▓
▓  #0 /vendor/fortrabbit/craft-copy/src/services/DeployConfig.php(53):
▓  fortrabbit\Copy\services\DeployConfig->getConfigDataFromFile()
▓  #1 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(174): fortrabbit\Copy\services\DeployConfig->get()
▓  #2 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(92):
▓  fortrabbit\Copy\commands\SetupAction->setupRemote(Object(fortrabbit\Copy\models\DeployConfig))
▓  #3 [internal function]: fortrabbit\Copy\commands\SetupAction->run()
▓  #4 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
▓  #5 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
▓  #6 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('setup', Array)
▓  #7 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('setup', Array)
▓  #8 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/setup', Array)
▓  #9 /vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('copy/setup', Array)
▓  #10 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('copy/setup', Array)
▓  #11 /vendor/yiisoft/yii2/base/Application.php(386):
▓  yii\console\Application->handleRequest(Object(craft\console\Request))
▓  #12 /craft(22): yii\base\Application->run()
▓  #13 {main}
```

**Comment by ostark** [comment]
Hi Brian,

good catch, I hope RC5 solves it for you (please update)
https://github.com/fortrabbit/craft-copy/releases/tag/1.0.0-RC5

Oli

**Comment by bryanjhickey** [comment]
This resolved the issue. Thanks.
