### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by XhmikosR** [fortrabbit/craft-copy#4]
Hi, there.

I know you state in README.md no Windows support, but being I'm personally on Windows most of the time, I could really benefit from this.

Thanks!

**Comment by ostark** [comment]
Well, it's basically not supported as our Windows knowledge is very limited. 
If you can provide any help, feel free to contribute.

**Comment by XhmikosR** [comment]
I have XAMPP set up already, but it seems rsync is needed too. I will try with MSYS2 and see how it goes.

**Comment by XhmikosR** [comment]
@ostark: I finally managed to test this on Windows.

Some things work, others don't.

My setup is msys2, with openssh, rsync and gzip packages installed for msys2. For LAMP I use XAMPP so I add them in my PATH:

```shell
export PATH="/C/xampp-portable-72/php":"/C/xampp-portable-72/mysql/bin":$PATH
cd /c/Users/xmr/Desktop/foo
```

The following commands work fine:

```
copy/setup
copy
copy/info
copy/db/to-file
```

These don't work:

* `./craft copy/db/down` fails with

   ```shell
    xmr@xmr-PC MSYS /c/Users/xmr/Desktop/foo
    $ ./craft copy/db/down

    Export DB remote - import locally: foostaging
    ---------------------------------------------------

     Are you sure? (yes/no) [yes]:
     >

    Creating dump on remote (./storage/craft-copy-transfer.sql)
    =================>----------------------------------------------------  25 %
    time:  6 secs/24 secs



     [ERROR] ssh foostaging@deploy.us1.frbit.com 'cat ./storage/craft-copy-transfer.sql
             | gzip' | zcat > ./storage/craft-copy-transfer.sql
             'gzip'' is not recognized as an internal or external command,
             operable program or batch file.


             fortrabbit\Copy\exceptions\RemoteException

             in C:\Users\xmr\Desktop\foo\vendor\fortrabbit\craft-copy\src\services\Ssh.php: 108


    ▓
    ▓  Stack trace:
    ▓
    ▓  #0 \vendor\fortrabbit\craft-copy\src\commands\DbDownAction.php(60):
    ▓  fortrabbit\Copy\services\Ssh->download('./storage/craft...', './storage/craft...')
    #1 [internal function]:
    ▓  fortrabbit\Copy\commands\DbDownAction->run()
    #2 \vendor\yiisoft\yii2\base\Action.php(94):
    ▓  call_user_func_array(Array, Array)
    #3 \vendor\yiisoft\yii2\base\Controller.php(157):
    ▓  yii\base\Action->runWithParams(Array)
    #4 \vendor\yiisoft\yii2\console\Controller.php(148):
    ▓  yii\base\Controller->runAction('db/down', Array)
    #5 \vendor\yiisoft\yii2\base\Module.php(528):
    ▓  yii\console\Controller->runAction('db/down', Array)
    #6 \vendor\yiisoft\yii2\console\Application.php(180):
    ▓  yii\base\Module->runAction('copy/db/down', Array)
    #7 \vendor\yiisoft\yii2\console\Application.php(147):
    ▓  yii\console\Application->runAction('copy/db/down', Array)
    #8 \vendor\yiisoft\yii2\base\Application.php(386):
    ▓  yii\console\Application->handleRequest(Object(craft\console\Request))
    #9 \craft(22): yii\base\Application->run()
    #10
    ▓  {main}
    ▓
    ```

* `./craft copy/assets/down` fails with the following, but wrongfully shows as succeeded:

    ```shell
    xmr@xmr-PC MSYS /c/Users/xmr/Desktop/foo
    $ ./craft copy/assets/down web/images/

    Copy assets down
    ----------------

    +-----------------+---------------------------------------+
    | Key             | Value                                 |
    +-----------------+---------------------------------------+
    | Asset directory | ./web/images/                         |
    +-----------------+---------------------------------------+
    | SSH remote      | foostaging@deploy.us1.frbit.com |
    +-----------------+---------------------------------------+
    | Dry run         | false                                 |
    +-----------------+---------------------------------------+

     Are you sure? (yes/no) [yes]:
     >

    Rsync started
    -------------

    The system cannot find the path specified.

    done
    ------
    ```

I haven't tried the other commands yet.

**Comment by XhmikosR** [comment]
If I execute the same rsync command manually from msys2 then it works :S

```
/usr/bin/rsync -Lva --rsh 'ssh' foostaging@deploy.us1.frbit.com:./web/images/ ./web/images/
```

**Comment by ostark** [comment]
let's try [prepared commands](https://symfony.com/blog/new-in-symfony-4-1-prepared-commands). In dev-master we rely on 4.1 now, so we can make use of auto-escaping when using array style arguments instead of a string. 
https://github.com/symfony/process/blob/42e1ccfd64ecede16b2dbfa9cc1972445cdc2a97/Process.php#L1570

**Comment by XhmikosR** [comment]
Ah, that's too bad :/

**Comment by XhmikosR** [comment]
There must be some way we can workaround this, even conditionally. Also, have you thought about using a php SSH library like phpseclib?

This at least will solve one of the issues. The other one with rsync, needs to be fixed upstream.

**Comment by XhmikosR** [comment]
Any updates @ostark?

**Comment by ostark** [comment]
I'll have another look

**Comment by yenyrubiano** [comment]
Hello @ostark any news about this issue?
I am experiencing the same "fortrabbit\Copy\exceptions\RemoteException" issue on macOS after updating my system to Mojave.

**Comment by XhmikosR** [comment]
This is specific to Windows @yenyrubiano and unrelated to anything else. You should make another issue or try and fix your setup.

**Comment by ostark** [comment]
I gave up. The best advice we can give is using the Ubuntu subsystem for Windows.

**Comment by XhmikosR** [comment]
That's too bad.
