### ISSUE TITLE
[ERROR] Call to undefined method Stringy\Stringy::snakeize() during setup

### ISSUE THREAD

**Issue by swthate** [fortrabbit/craft-copy#45]
**Versions**
`Craft: 3.3.0.1`
`PHP: 7.3.7`

**What I tried to do**
Setup the plugin via command-line after install

**What happened...**
Error, call to an undefined method Stringy/Stringy::snakeize()

After requiring craft-copy in the terminal I was greeted with this message:
```
Warning: Ambiguous class resolution, "Stringy\Stringy" was found in both "/Users/steven/Code/vetscripts/vendor/danielstjules/stringy/src/Stringy.php" and "/Users/steven/Code/vetscripts/vendor/voku/stringy/src/Stringy.php", the first will be used.

Warning: Ambiguous class resolution, "Stringy\StaticStringy" was found in both "/Users/steven/Code/vetscripts/vendor/danielstjules/stringy/src/StaticStringy.php" and "/Users/steven/Code/vetscripts/vendor/voku/stringy/src/StaticStringy.php", the first will be used.
```

Since this was just a warning and it seemed to suggest it would take care of it on its own (just using the first one), I figured it would be safe to proceed. After installing the plugin I ran `$ php craft copy/setup`, gave it the name of the fortrabbit app, and then after giving it the name of production I got this error message:

```
                                                                                                                        
 [ERROR] Call to undefined method Stringy\Stringy::snakeize()                                                           
         Error                                                                                                          
         in /Users/steven/Code/vetscripts/vendor/craftcms/cms/src/helpers/StringHelper.php: 1645                        

▓                                                                                                                       
▓  Stack trace:                                                                                                         
▓                                                                                                                       
▓  #0 /vendor/fortrabbit/craft-copy/src/models/DeployConfig.php(62): craft\helpers\StringHelper::toSnakeCase('app')     
▓  #1 /vendor/fortrabbit/craft-copy/src/services/DeployConfig.php(88): fortrabbit\Copy\models\DeployConfig->toArray()   
▓  #2 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(153):                                                  
▓  fortrabbit\Copy\services\DeployConfig->persist(Object(fortrabbit\Copy\models\DeployConfig))                          
▓  #3 /vendor/fortrabbit/craft-copy/src/commands/SetupAction.php(67):                                                   
▓  fortrabbit\Copy\commands\SetupAction->writeDeployConfig('vetscripts', 'us1', 'production')                           
▓  #4 [internal function]: fortrabbit\Copy\commands\SetupAction->run()                                                  
▓  #5 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)                                      
▓  #6 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)                              
▓  #7 /vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('setup', Array)                  
▓  #8 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('setup', Array)                      
▓  #9 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/setup', Array)                
▓  #10 /vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('copy/setup', Array)    
▓  #11 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('copy/setup', Array)     
▓  #12 /vendor/yiisoft/yii2/base/Application.php(386):                                                                  
▓  yii\console\Application->handleRequest(Object(craft\console\Request))                                                
▓  #13 /craft(22): yii\base\Application->run()                                                                          
▓  #14 {main}                                                                                                           
▓ 
```

**Comment by ostark** [comment]
@swthate Thanks for letting us know. 
I'd say not our fault. Maybe @angrybrad knows more, since he touched the string helper recently.

**Comment by ostark** [comment]
Ah, Craft uses the fork (voku/stringy) of `danielstjules/stringy`.
Maybe all full `composer update` helps ...

**Comment by swthate** [comment]
It did update `voku/string` and one other package:
```
$ composer update craftcms/cms --with-all-dependencies
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating voku/urlify (4.1.0 => 4.1.1): Downloading (100%)         
  - Updating opis/closure (3.3.1 => 3.4.0): Downloading (100%)         
Writing lock file
Generating optimized autoload files
Warning: Ambiguous class resolution, "Stringy\Stringy" was found in both "/Users/steven/Code/vetscripts/vendor/danielstjules/stringy/src/Stringy.php" and "/Users/steven/Code/vetscripts/vendor/voku/stringy/src/Stringy.php", the first will be used.
Warning: Ambiguous class resolution, "Stringy\StaticStringy" was found in both "/Users/steven/Code/vetscripts/vendor/danielstjules/stringy/src/StaticStringy.php" and "/Users/steven/Code/vetscripts/vendor/voku/stringy/src/StaticStringy.php", the first will be used.
```

But I get the same error result I described above after trying to set the environment during `copy/setup`. :(

Hopefully @angrybrad has a stringy idea.

**Comment by angrybrad** [comment]
@swthate it sounds like there are some old `danielstjules/stringy` files left behind.  Can you nuke `composer.lock` and `vendor`, then re-run `composer update` to pull down a fresh set of files?

**Comment by ostark** [comment]
Right, if nothing helps - use the hammer: nuke `composer.lock` and `/vendor`.
I'm closing this, as it is not directly related to the plugin.

**Comment by swthate** [comment]
Hammerzeit!

That did the trick, thanks @ostark and @angrybrad 🙏
