### ISSUE TITLE
Add storage path config item

### ISSUE THREAD

**Issue by joshuabaker** [fortrabbit/craft-copy#68]
If you have a different install path (e.g. `/api`) the plugin fails to upload the `craft-copy-transfer.sql` file.

Please can we add a `remote_storage_path` config variable, or similar, to fix this.

### Example

```
➜ php craft copy/db/up


▶ [production *******] Export local DB and import on remote.

 Are you sure? (yes/no) [no]:
 > yes

Creating local dump
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  25 %
time:   1 sec/4 secs



 [ERROR] cat ./storage/craft-copy-transfer.sql | gzip | ssh
         *******@deploy.eu2.frbit.com "zcat > ./storage/craft-copy-transfer.sql"
         bash: ./storage/craft-copy-transfer.sql: No such file or directory

         –––––––––––––––––––––––  ∙ƒ









         fortrabbit\Copy\Exceptions\RemoteException

         in /*******/api/vendor/fortrabbit/craft-copy/src/Services/Ssh.php:
         58


▓
▓  Stack trace:
▓
▓  #0 /vendor/fortrabbit/craft-copy/src/Actions/DbUpAction.php(80):
▓  fortrabbit\Copy\Services\Ssh->upload('./storage/craft...', './storage/craft...')
▓  #1 [internal function]: fortrabbit\Copy\Actions\DbUpAction->run(NULL)
▓  #2 /vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
▓  #3 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
▓  #4 /vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('db/up', Array)
▓  #5 /vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('db/up', Array)
▓  #6 /vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('copy/db/up', Array)
▓  #7 /vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('copy/db/up', Array)
▓  #8 /vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('copy/db/up', Array)
▓  #9 /vendor/yiisoft/yii2/base/Application.php(386):
▓  yii\console\Application->handleRequest(Object(craft\console\Request))
▓  #10 /craft(23): yii\base\Application->run()
▓  #11 {main}
▓
```

**Comment by ostark** [comment]
ACK. But I could not find an elegant way to fix it. I could use `getStoragePath()`, but it does not help if the local and the remote differs.

**Comment by joshuabaker** [comment]
@ostark Would that not just be changing the below to reference `CRAFT_STORAGE_PATH`?

https://github.com/fortrabbit/craft-copy/blob/455cbad03fe09cd17dc9fecd548ca00ea5bd36e3/src/Actions/DbUpAction.php#L37

**Comment by joshuabaker** [comment]
Thank you 🙏🏻

**Comment by ostark** [comment]
Well, just did some housekeeping, but did not merge the proposed change.

**Comment by frank-laemmer** [comment]
We have not forgot about it, but it is not planned for any future release.

**Comment by joshuabaker** [comment]
Going to close this as stale/unplanned.
